### ISSUE TITLE
After update not working

### ISSUE THREAD

**Issue by portalek** [node-red-contrib/node-red-contrib-mikrotik#23]
After updating to version 0.40, I have only this error and no connection to mikrotik.

"name":"RosException","errno":"SOCKTMOUT","message":"Timed out after 10 seconds"

Anybody with same problem?

**Comment by konne** [comment]
Hi, I'm usually only working with the git version. But I tested now the exact NPM and it works great.

What is your RouterOS Version?

Please do the following steps so that I can understand why this is not working as expected on your system:

go into the connection settings of the MikroTik node ...
1. and just press approve/save again -> TEST
2. and write the data again into the dialog -> TEST
3. delete the connection and add it again -> TEST

Thx

**Comment by portalek** [comment]
Hi, I tried 2 versions RouterOS v6.43.16 and RouterOS v6.47.7

I tried 1,2,3 with no change.

There is no connection log in mikrotik log, in previous version there is api login and logout.

**Comment by konne** [comment]
Hi Portalek, do we have a chance to make a short remote session (teams, zoom,...) together so that I can debug your issue.

**Comment by portalek** [comment]
no problem, prefferable teamviewer, is here any chance of PM?

**Comment by konne** [comment]
there are no private message :-)
please write me an email: konrad  at mattheis.name

**Comment by konne** [comment]
@portalek totally strange, I just installed the exact same docker container on my qnap, and its working like a charm,
I have no idea. I will close this topic for now
