### ISSUE TITLE
Unable to enable  / disable interface

### ISSUE THREAD

**Issue by Cooper-Dale** [node-red-contrib/node-red-contrib-mikrotik#42]
**Describe the bug**
I am inable to enable or disable any ethernet or wireless interface usign raw command.
**To Reproduce**
`[
    "/interface/enable",
    "=numbers=7"
]`
returns
`Error executing cmd[["/interface/enable","=numbers=7",".tag=j1rkch4mkc"]]: {}`
full flow
`[{"id":"23b967fa1e0538d1","type":"mikrotik","z":"ed0ca72e.2817a8","device":"69c2a6db.c414c8","name":"","action":"9","command":"","command-type":"str","x":920,"y":3000,"wires":[["318e156a616d8ed5"]]},{"id":"602704237dd3122f","type":"inject","z":"ed0ca72e.2817a8","name":"sfp1 enable","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"[\"/interface/enable\",\"=numbers=7\"]","payloadType":"json","x":770,"y":3000,"wires":[["23b967fa1e0538d1"]]},{"id":"318e156a616d8ed5","type":"debug","z":"ed0ca72e.2817a8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":true,"complete":"payload","targetType":"msg","statusVal":"payload[0][\".id\"]","statusType":"msg","x":1090,"y":3000,"wires":[]},{"id":"69c2a6db.c414c8","type":"mikrotik-device","host":"192.168.1.1","port":"8728","username":null,"password":null,"ssl":"api"}]`

**Expected behavior**
succes with every command
i tried many variations like set enable, but no success

**Comment by 0nikola1** [comment]
Few months passed since you posted here but now I tested and it works for me with for both disable and enable with sfp on hAP ac with ROS v6.49. Do you still have issue with it and if so which device is it and which ROS version?
 ` [{"id":"23b967fa1e0538d1","type":"mikrotik","z":"589710b8.068a1","device":"","name":"","action":"9","command":"","command-type":"str","x":660,"y":1020,"wires":[["318e156a616d8ed5"]]},{"id":"318e156a616d8ed5","type":"debug","z":"589710b8.068a1","name":"","active":true,"tosidebar":true,"console":false,"tostatus":true,"complete":"payload","targetType":"msg","statusVal":"payload[0][\".id\"]","statusType":"msg","x":830,"y":1020,"wires":[]},{"id":"106b5aa2.b9d515","type":"inject","z":"589710b8.068a1","name":"sfp1 enable","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"[\"/interface/enable\",\"=numbers=5\"]","payloadType":"json","x":450,"y":1020,"wires":[["23b967fa1e0538d1"]]},{"id":"3090ed4b.f7dd62","type":"inject","z":"589710b8.068a1","name":"sfp1 disable","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"[\"/interface/disable\",\"=numbers=5\"]","payloadType":"json","x":430,"y":1060,"wires":[["23b967fa1e0538d1"]]}] `

**Comment by konne** [comment]
@Cooper-Dale if you still haven an issue please reopen.

**Comment by Cooper-Dale** [comment]
Prolem was with the policy, I forgot to tick **write** permission for the node-red group policies.
I was using ROS v6.48, now 7.1
